### ISSUE TITLE
Consistent connection key

### ISSUE THREAD

**Issue by basz** [prooph/pdo-snapshot-store#19]
A minor inconsistency; Throughout the various components the connection configuration key for persistency connections. Only in the snapshot packages 'connection_service' is the mandatory key.

https://github.com/search?q=org%3Aprooph+connection_service&type=Code

Dunno how to fix this without a BC...

**Comment by prolic** [comment]
We can introduce `connection` and fall back to `connection_service` if that
key doesn't exist.

**Comment by basz** [comment]
But we can’t just make Connection required as that would break existentiële installs. Unless we can translate one to the other before the required properties are checked.

I’ll investigate.

> Op 25 mrt. 2018 om 14:44 heeft Sascha-Oliver Prolic <notifications@github.com> het volgende geschreven:
> 
> We can introduce `connection` and fall back to `connection_service` if that
> key doesn't exist.
>

**Comment by prolic** [comment]
@sandrokeil any ideas?

**Comment by sandrokeil** [comment]
I don't think we can solve this with interop config. We need something like an alias but I don't want to add such a feature. This is not really an issue but we can fix it in next major versions.

Or do you want to introduce `connection` and keep `connection_service` key? We could remove `connection_service`  from mandatory list and update docs to use `connection`. Then it would fail with an service not found exception if not configured properly. The factory could take care to check which key should be used.

**Comment by basz** [comment]
what if we;
1. remove the `connection_sercvice` from mandatory option
2. throw MandatoryOptionNotFoundException::missingOption($this->dimensions(), 'connection' if neither `connection` or `connection_service` is found in `__invoke`.
3. Oh, and update docs

Behaviour would be equal to what would happen now except for the reported key in the exception.

**Comment by sandrokeil** [comment]
Good idea, I think we can do this manually.
